import Header from "@/components/Header";
import Link from "next/link";

export const metadata = {
  title: "Hikmah Solution",
  description: "Generated by create next app",
};

export default async function BlogLayout({ children, params }) {
  const { id } = await params;

  let competitions = [];

  try {
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/admin/competition`,
      {
        next: { revalidate: 0 },
      }
    );

    if (!res.ok) {
      throw new Error(`Failed to fetch: ${res.status}`);
    }

    const data = await res.json();

    // console.log(data);

    competitions = data?.competitions || [];
  } catch (error) {
    console.error("Error fetching blog data:", error);
  }

  const competitiionTitle = competitions.find(
    (competition) => competition._id === id
  )?.title;

  // console.log(competitions);

  return (
    <div>
      <Header />
      <div className=" relative w-full h-[30rem] bg-green-800  ">
        <h2 className="w-full h-full text-[2rem] flex items-center font-medium text-[#fff] text-center line-clamp-1 max-w-[30rem] mx-auto truncate ">
          {competitiionTitle}
        </h2>
      </div>
      <div
        className={` flex gap-5 lg:flex-row flex-col justify-between max-w-[1400px] mx-auto pt-[2rem] px-3 `}
      >
        <div className=" w-full ">{children}</div>
        <div className=" w-full lg:w-[30rem] lg:pt-0 pt-[2rem] pb-[2rem] px-3 bg-slate-50 rounded-md ">
          <h3 className=" text-[1.5rem] font-semibold mt-2 ">
            Related Competitiions
          </h3>
          <div className=" space-y-2 mt-[2rem] ">
            {competitions &&
              competitions.map((competition, idx) => (
                <div key={idx} className=" w-full ">
                  <Link
                    href={`/competitiions/${competition?._id}`}
                    className=" block py-2 px-2 w-full bg-slate-100 rounded-md line-clamp-2 truncate text-green-500 text-[1.2rem] font-medium "
                  >
                    {competition?.title}
                  </Link>
                </div>
              ))}
          </div>
        </div>
      </div>
    </div>
  );
}
