import Header from "@/components/Header";
import Link from "next/link";

export const metadata = {
  title: "Hikmah Solution",
  description: "Generated by create next app",
};

export default async function BlogLayout({ children, params }) {
  const { id } = await params;

  let blogs = [];

  try {
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/admin/blogs`,
      {
        next: { revalidate: 0 },
      }
    );

    if (!res.ok) {
      throw new Error(`Failed to fetch: ${res.status}`);
    }

    const data = await res.json();

    blogs = data?.blogs || [];
  } catch (error) {
    console.error("Error fetching blog data:", error);
  }

  const blogTitle = blogs.find((blog) => blog._id === id)?.title;

  // console.log(blogs);

  return (
    <div>
      <Header />
      <div className=" relative w-full h-[30rem] bg-green-800  ">
        <div className=" w-full h-full text-[3rem] font-medium text-[#fff] flex items-center justify-center ">
          {blogTitle}
        </div>
      </div>
      <div
        className={` flex gap-5 lg:flex-row flex-col justify-between max-w-[1400px] mx-auto pt-[2rem] px-3 `}
      >
        <div className=" w-full ">{children}</div>
        <div className=" w-full lg:w-[30rem] lg:pt-0 pt-[2rem] pb-[2rem] px-3 bg-slate-50 rounded-md ">
          <h3 className=" text-[1.5rem] font-semibold mt-2 ">Related Blogs</h3>
          <div className=" space-y-2 mt-[2rem] ">
            {blogs &&
              blogs.map((blog, idx) => (
                <div key={idx} className=" w-full ">
                  <Link
                    href={`/blogs/${blog?._id}`}
                    className=" block py-2 px-2 w-full bg-slate-100 rounded-md text-green-500 text-[1.2rem] font-medium "
                  >
                    {blog?.title}
                  </Link>
                </div>
              ))}
          </div>
        </div>
      </div>
    </div>
  );
}
