import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { DataProvider } from "@/context/Context";
import { ToastContainer } from "react-toastify";



export const metadata: Metadata = {
  title: "Hikmah Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DataProvider>
    <html lang="en">
      <body className={`  `}>
        
        {children}
        <ToastContainer />
      </body>
    </html>
    </ DataProvider >
  );
}
